### ISSUE TITLE
no branch appears installable

### ISSUE THREAD

**Issue by anderbubble** [irods/irods_rule_engine_plugin_logical_quotas#11]
I'm trying to get our iRODS deployment updated for a push to production, but this plugin doesn't appear to be working.

- the 4-2-stable branch requires irods 4.2.8, which isn't released
- the master branch generates errors when built on RHEL7.6

[build-errors.txt](https://github.com/irods/irods_rule_engine_plugin_logical_quotas/files/4238919/build-errors.txt)

How can I install this today?

**Comment by trel** [comment]
Yes, we recently readied the plugin for initial release alongside 4.2.8 (2c3d5d96e052c1b40ed26800672aaeee732fc693).

I believe you can build the prior commit (00be6d128def0ef443a396601d00c1c705190c18) against 4.2.7, but we're not planning on officially supporting that version at this time.

**Comment by trel** [comment]
closing - we're releasing this ASAP with 4.2.8.
