### ISSUE TITLE
incorrect access to quota metadata as rodsuser and rodsadmin

### ISSUE THREAD

**Issue by anderbubble** [irods/irods_rule_engine_plugin_logical_quotas#2]
I was able to remove these keys as a rodsuser (not desired) but not as a rodsadmin (which would be desired). Maybe allowing this kind of io isn't possible for rodsadmin; but I tried because we got stuck. (See #1.)

```
[root@irods1 ~]# sudo -u irods imeta rmw -C /curcZone/home/joan5896 irods::logical_quotas::% %
Nov  4 16:29:41 pid:20147 NOTICE: rsModAVUMetadata: rcModAVUMetadata failed
remote addresses: 10.225.160.101 ERROR: rcModAVUMetadata failed with error -818000 CAT_NO_ACCESS_PERMISSION
```

```
[joan5896@admin2 ~]$ imeta rmw -C /curcZone/home/joan5896 irods::logical_quotas::% %
```

**Comment by korydraughn** [comment]
This is now handled via the [metadata_guard](https://github.com/irods/irods_rule_engine_plugin_metadata_guard) rule engine plugin.
