### ISSUE TITLE
Add rule that returns the quota information in a parsable format

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_rule_engine_plugin_logical_quotas#28]
- [x] master
- [x] 4-2-stable
---
The rule should take an operation and collection and return the quota information as JSON.

### Input
```javascript
{
    "operation": "logical_quotas_stat", // <-- This seems like a fun name.
    "collection": "/path/to/collection"
}
```
### Output
The keys will have the names defined under `plugin_specific_configuration::metadata_attribute_names`.
```javascript
{
    "maximum_number_of_data_objects": integer,
    "maximum_size_in_bytes": integer,
    "total_number_of_data_objects": integer,
    "total_size_in_bytes": integer
}
```

**Comment by trel** [comment]
is that 'stat' for 'status' or for 'statistics'?

**Comment by korydraughn** [comment]
**status** most likely. I chose that as a possibility because the `stat` command came to mind while writing the example, but im up for suggestions (e.g. `_get_quota_info`, `_get_quotas`, etc).

**Comment by trel** [comment]
i like the namespacing provided by `logical_quotas_`...

and `status` (or `info`) seems fine to me for the operation we're providing.

hmmm, perhaps `get_logical_quotas_info` or `logical_quotas_get_info`.... naming is hard.

are there other operations we're interested in providing through this type of rule mechanism?  that could help define the naming convention... if any.

**Comment by trel** [comment]
went with `logical_quotas_get_collection_status`
