### ISSUE TITLE
CAT_NO_ACCESS_PERMISSION error when using LQ operations on a group collection

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_rule_engine_plugin_logical_quotas#35]
- [x] main
- [x] 4-2-stable
---
Once the logical quota is used on a group collection then the following error has been received.

```
irods@irods$ irule -r irods_rule_engine_plugin-logical_quotas-instance '{"operation": "logical_quotas_start_monitoring_collection", "collection": "/tempZone/home/test"}' null ruleExecOut
remote addresses: 10.0.2.100 ERROR: rcExecMyRule error.  status = -1205000 RE_RUNTIME_ERROR
Level 0: cannot set metadata: Unknown error -818000
```

logs:
```
Feb 11 16:19:04 pid:135329 NOTICE: rsModAVUMetadata: rcModAVUMetadata failed
Feb 11 16:19:04 pid:135329 remote addresses: 10.0.2.100, ::1 ERROR: cannot set metadata: Unknown error -818000
Feb 11 16:19:04 pid:135329 remote addresses: 10.0.2.100, ::1 ERROR: rsExecMyRule : -1205000, [-]        /irods_plugin/src/handler.cpp:529:irods::error irods::handler::logical_quotas_count_total_number_of_data_objects(const std::string &, const irods::instance_configuration_map &, std::list<boost::any> &, irods::callback &) :  status [RE_RUNTIME_ERROR]  errno [] -- message [cannot set metadata: Unknown error -818000]
```

**Comment by trel** [comment]
What is a group collection?

Can you share the permissions on `/tempZone/home/test`?

```
$ ils -A /tempZone/home/test
```

**Comment by mstfdkmn** [comment]
A group collection is an irods group created by `iadmin mkgroup test`
The permission is "own" only for the group/collection itself, not for the rodsadmin which you suspect/I think explains the error.
As an rodsadmin the user rods cannot modify access to the group collection in this case "test" because he/she is not member of the group yet.
After `iadmin atg test rods`, the user rods can modify by doing `ichmod own rods /tempZone/home/test`
Then starts monitoring.

**Comment by trel** [comment]
Okay, so this is working as expected?

Or since logical quotas are defined and run only by admins (I think this is a true statement)... are we missing an ADMIN_KW somewhere?  @korydraughn

**Comment by trel** [comment]
Need to make this run for `rodsadmin`s without them having to manually update ACLs in the system.
