### ISSUE TITLE
When to use `logical_quotas_count_total_number_of_data_objects` and `logical_quotas_count_total_size_in_bytes`

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_rule_engine_plugin_logical_quotas#78]
I could not understand in which condition to use the `logical_quotas_count_total_number_of_data_objects` and `logical_quotas_count_total_size_in_bytes` operations. I execute them but I see nothing.

 If these are used to show the totals correctly in regards to the fact mentioned in README for relative values, then what is the difference between these operations and `logical_quotas_recalculate_totals`?

Thank you.

**Comment by korydraughn** [comment]
There's no specific reason to use `logical_quotas_count_total_number_of_data_objects` or `logical_quotas_count_total_size_in_bytes` over `logical_quotas_recalculate_totals`.

There exist as options for the admin. If the admin only monitored the number of data objects, then they may not want to pay for the additional work done by `logical_quotas_recalculate_totals`.

**Comment by mstfdkmn** [comment]
Thanks Kory. I guess it can be closed if okay for you.
