### ISSUE TITLE
Update script to use correct argument

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_rule_engine_plugin_logical_quotas#79]
## Bug Report
- [x] main
- [x] 4-2-stable
---
https://github.com/irods/irods_rule_engine_plugin_logical_quotas/blob/df75c52f6d8aa89a2b452aeb56626c2f944b5986/packaging/run_logical_quotas_test.py#L4

**Comment by trel** [comment]
Because the mtime plugin no longer exists separately?

**Comment by korydraughn** [comment]
This is a copy pasta. Logical Quotas doesn't rely on the mtime plugin in any way.

**Comment by korydraughn** [comment]
I don't think anything relies on this script. We should just remove it.
