### ISSUE TITLE
Run clang-format on all source files

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_rule_engine_plugin_logical_quotas#91]
- [x] main
- [x] 4-3-stable

git clang-format is introducing lots of wild misalignment into source code, by the insertion of tab characters

**Comment by korydraughn** [comment]
We can rename this issue to say format all source files.

**Comment by korydraughn** [comment]
Reopening for now. We'll repurpose this issue to handle formatting.

**Comment by korydraughn** [comment]
All good.

**Comment by d-w-moore** [comment]
Maybe this doesn't need to be an issue after all, since it was my understanding that was lacking.  So, we close this maybe ... unless we want clang-format commits to show up in our public history, tagged with this issue number.
